require "sinatra"
require "sinatra/contrib"

# This will restart sinatra every time the IDE is saved
require "sinatra/reloader" if development?

# READ ROUTE

# This is the what sinatra will look at when first on the site. It is the root stuff
get "/" do
  "Boilerplate for RESTful routes"
end

# This will return all of the results of a page as there are no specific parameters
# to determine what the server gets
get "/books" do
  "This will return all of the books within the storage medium"
end

# CREATE ROUTE

# This will get a HTML form and display it so that the user can input the relevant information
# That they want to be stored
get "/books/new" do
  "Return form for adding a book"
end

# When the user clicks the submit button of the form (displayed above), the post will retrieve
# the information that the user has inputted and will add it to the storage medium being used by
# the website via the controller
post "/books/new" do
  "The information has been added to storage"
end

# This allows the client to get a specific result using an ID that is either generated by the storage medium
# or is specified by the user in the URL
get "/books/:id" do
  "This will return a specific book based on the ID that the user puts in or that is assigned from storage"
end
